platform :ios, '14.0'
use_frameworks!

target 'TestApp' do
 pod 'SAPCommon', :podspec => "../SAPCommon/7.0.0/SAPCommon.podspec"
 pod 'SAPFoundation', :podspec => "../SAPFoundation/7.0.0/SAPFoundation.podspec"
 pod 'SAPFiori', :podspec => "../SAPFiori/7.0.0/SAPFiori.podspec"
 pod 'SAPFioriFlows', :podspec => "../SAPFioriFlows/7.0.0/SAPFioriFlows.podspec"
 pod 'SAPOData', :podspec => "../SAPOData/7.0.0/SAPOData.podspec"
 pod 'SAPOfflineOData', :podspec => "../SAPOfflineOData/7.0.0/SAPOfflineOData.podspec"
 pod 'SAPML', :podspec => "../SAPML/7.0.0/SAPML.podspec"
end
